### ISSUE TITLE
legal notice, 

### ISSUE THREAD

**Issue by DavidBrockway** [tommytran732/SummerHoax#2]
Dear Tommy,

I would like to inform you legal action has been taken against you from today.

Thank you,

David

**Comment by DavidBrockway** [comment]
DMCA  request against you are with OVH Cloud US,

OVHUCloud US legal team, have been in contact and are taking action.

**Comment by tommytran732** [comment]
First of all, this is not even remotely close to a legal notice.
Secondly, I am still waiting for a formal letter from your lawyer that you has been promising for quite some time now.
Thirdly, what are you sending a DMCA regarding to?

**Comment by DavidBrockway** [comment]
Hello,

I am taking action against Revenant & Tommy,

My lawyer has filed for 4 DMCA request, to OVH, NameCheap, OVH

Cloudflare has responded and has contacted OVH & Tommy
OVH Has responded is taking the content down.

https://media.discordapp.net/attachments/670742358576463873/671616248756305920/Screenshot_20200128-072231.jpg?width=568&height=1231

**Comment by tommytran732** [comment]
Where did they say they will take it down? It is nowhere mentioned in your screenshot lol.

**Comment by tommytran732** [comment]
Okay, looks like OVH & Github have called you out for your not even remotely close to valid "DMCA" request, so I am closing this issue here.
